#!/bin/bash

# exit when any command fails
set -e

# check if CHANGELOG was added
log=`sed -n '/^## '$1'/p;q' CHANGELOG.md`
if [ -z "$log" ]
then
  echo "CHANGELOG for version $1 must be added! (The CHANGELOG.md file must start with '## $1')"; exit 1;
else
  echo "CHANGELOG added, releasing version $1"
fi

# set version in README.md
gsed -i 's/pod '\'RenVMSwift\'', '\''~> '.*''\''/pod '\'RenVMSwift\'', '\''~> '$1'\'\''/g' README.md
gsed -i 's/RenVMSwift", from: "'.*'")/RenVMSwift", from: "'$1'")/g' README.md

# set version in podspec
gsed -i 's/s.version.*= '.*'/s.version          = '\'''$1'\'\''/g' RenVMSwift.podspec

# lint podspec
pod lib lint RenVMSwift.podspec --allow-warnings

# commit and tag
git add 'RenVMSwift.podspec' 'README.md'
git commit -m "feat: upversion to '$1'"
git tag ''$1''
git push origin master --tags

# upload in cocoapods
pod trunk push SolanaSwift.podspec --allow-warnings
